//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSDatPhong
    {
        public string TenPhong { get; set; }
        public System.DateTime NgayCheckIn { get; set; }
        public string SDT { get; set; }
        public bool CheckIn { get; set; }
        public int ThoiGianLuuTru { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
